version: '3.8'

services:
  # 1. Database (MongoDB Local)
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db # Giữ lại dữ liệu khi tắt container

  # 2. Backend (Node.js)
  server:
    build: .
    ports:
      - "5000:5000"
    environment:
      # Kết nối tới container 'mongo' thay vì cloud
      - MONGO_URI=mongodb://mongo:27017/todo_app_docker
      - PORT=5000
    depends_on:
      - mongo

  # 3. Frontend (React + Vite)
  client:
    build: ./client
    ports:
      - "5173:5173"
    environment:
      # React chạy ở trình duyệt máy bạn, nên gọi API qua localhost:5000
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - server

volumes:
  mongo_data: